province = {
	"Hebei": "HE",
	"Shanxi": "SX",
	"Liaoning": "LN", 
	"Jilin": "JL",
	"Heilongjiang": "HL",
	"Jiangsu": "JS",
	"Zhejiang": "ZJ",
	"Anhui": "AH",
	"Fujian": "FJ",
	"Jiangxi": "JX",
	"Shandong": "SD",
	"Henan": "HA",
	"Hubei": "HB",
	"Hunan": "HN",
	"Guangdong": "GD",
	"Hainan": "HI",
	"Sichuan": "SC",
	"Guizhou": "GZ",
	"Yunnan": "YN",
	"Shaanxi": "SN",
	"Gansu": "GS",
	"Qinghai": "QH",
	"Taiwan": "TW"
}

prov_capitals = {
	"Hebei": "Shijiazhuang",
	"Shanxi": "Taiyuan",
	"Liaoning": "Shenyang",
	"Jilin": "Changchun",
	"Heilongjiang": "Harbin",
	"Jiangsu": "Nanjing",
	"Zhejiang": "Hangzhou",
	"Anhui": "Hefei",
	"Fujian": "Fuzhou",
	"Jiangxi": "Nanchang",
	"Shandong": "Jinan",
	"Henan": "Zhengzhou",
	"Hubei": "Wuhan",
	"Hunan": "Changsha",
	"Guangdong": "Guangzhou",
	"Hainan": "Haikou",
	"Sichuan": "Chengdu",
	"Guizhou": "Guiyang",
	"Yunnan": "Kunming",
	"Shaanxi": "Xi'an",
	"Gansu": "Lanzhou",
	"Qinghai": "Xining",
	"Taiwan": "Taipei"
}
